project_id = "nbrugrwckgcoogfuhywu"

[functions.check-fingerprint]
verify_jwt = false

[functions.register-fingerprint]
verify_jwt = false

[functions.resolver-tpc]
verify_jwt = false

[functions.preparar-teste]
verify_jwt = false

[functions.resolver-matematica]
verify_jwt = false

[functions.verificar-pagamento]
verify_jwt = false

[functions.explicar-melhor]
verify_jwt = false

[functions.resumo-defesa]
verify_jwt = false
